[package]
name = "telemetry"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
bytes = "1.10.1"
crc = "3.3.0"
prost = "0.14.1"
prost-derive = "0.14.1"
serialport = "4.7.2"
thiserror = "2.0.12"
tokio = { version = "1.45.1", features = ["full"] }
