name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      # ── 1. Checkout repo ─────────────────────────────────────────────────────
      - uses: actions/checkout@v4

      # ── 2. Rust tool-chain (stable) ──────────────────────────────────────────
      - uses: dtolnay/rust-toolchain@stable

      # ── 3. Node.js (v20) ─────────────────────────────────────────────────────
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # ── 4. pnpm (v8) ─────────────────────────────────────────────────────────
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false          # we'll run install ourselves

      # ── 5. Front-end dependencies ───────────────────────────────────────────
      - name: Install front-end deps
        run: pnpm install --no-frozen-lockfile
        working-directory: apps/gcs-desktop

      # ── 6. Rust tests across the workspace ──────────────────────────────────
      - name: Cargo tests
        run: cargo test --workspace --all-features --verbose
